name: "Deploy and Instrument Allset Hosted App"
description: "Builds and deploys an Allset web app to firebase hosting, and adds instrumentation like Sentry Releases."

inputs:
  environment:
    description: "Set the environment for this release. E.g. 'edge', 'staging', or 'production'."
    required: true
  release_version:
    description: "The version string to associate with this release"
    required: true

  firebase_token:
    description: "The CI Token used to interact with Firebase"
    required: true
  firebase_project:
    description: "The name of the Firebase hosting project being deployed to"
    required: true

  node_version:
    description: "The version of node to use for the build"
    required: false
    default: "16.5.0"

runs:
  using: "composite"
  steps:
    - name: Install NodeJS for Github Actions
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm --production ci
      shell: bash

    - name: Install firebase-tools
      run: npm i -g firebase-tools
      shell: bash

    - name: Package application
      run: npm run build:${{ inputs.environment }}
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.release_version }}

    - name: Change firebase project to use proper environment
      run: firebase use ${{ inputs.environment }}
      shell: bash
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase_token }}

    - name: Firebase apply targets
      run: firebase target:apply hosting ${{ inputs.environment }} ${{ inputs.firebase_project }}
      shell: bash
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase_token }}

    - name: Deploy to Firebase
      run: firebase deploy --only hosting:${{ inputs.environment }}
      shell: bash
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase_token }}
