name: "Deploy and Instrument Allset Hosted App"
description: "Builds and deploys an Allset web app to firebase hosting, and adds instrumentation like Sentry Releases."

inputs:
  environment:
    description: "Set the environment for this release. E.g. 'edge', 'staging', or 'production'."
    required: true
  release_version:
    description: "The version string to associate with this release"
    required: true

  service_account_json:
    description: "GCP Service Account credentials json used to authenticate for deploys"
    required: true

  firebase_project:
    description: "The name of the Firebase hosting project being deployed to"
    required: true

  package_token:
    description: "The Github packages token to use for private NPM Repos"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install NodeJS for Github Actions
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Authenticate with Github Packages
      run: npm set '//npm.pkg.github.com/:_authToken' ${{ inputs.package_token }}
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Install firebase-tools
      run: npm i -g firebase-tools
      shell: bash

    - name: Package application
      run: npm run build:${{ inputs.environment }}
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.release_version }}

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.service_account_json }}

    - name: Change firebase project to use proper environment
      run: firebase use ${{ inputs.environment }}
      shell: bash

    - name: Firebase apply targets
      run: firebase target:apply hosting ${{ inputs.environment }} ${{ inputs.firebase_project }}
      shell: bash

    - name: Deploy to Firebase
      run: firebase deploy --only hosting:${{ inputs.environment }}
      shell: bash
